# Generated by Django 2.2 on 2020-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='main_photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
